name: Build ZMK firmware

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build Chocofi firmware
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Cache west modules
      uses: actions/cache@v4
      env:
        cache-name: cache-zephyr-modules
      with:
        path: |
          modules/
          tools/
          zephyr/
          bootloader/
          zmk/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - name: West Init
      run: west init -l config
    
    - name: West Update
      run: west update
    
    - name: West Zephyr export
      run: west zephyr-export
    
    - name: Build left half
      run: west build -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=chocofi_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
    
    - name: Rename left firmware
      run: cp build/zephyr/zmk.uf2 chocofi_left.uf2
    
    - name: Build right half
      run: west build --pristine -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=chocofi_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
    
    - name: Rename right firmware
      run: cp build/zephyr/zmk.uf2 chocofi_right.uf2
    
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: chocofi-firmware
        path: |
          chocofi_left.uf2
          chocofi_right.uf2